# Generated by Django 3.2.5 on 2021-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210721_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mime_type',
            field=models.CharField(default='jpeg', max_length=500),
        ),
    ]
